### ISSUE TITLE
Completar tarea 1

### ISSUE THREAD

**Issue by DrJoseGallardo** [GenomicsEducation/JaquelineFlores#1]
Estimada alumna, favor completar la tarea 1 de la semana pasada. Respecto de la tarea 2 de esta semana favor incluir un directorio llamado SCRIPT y en almacenar los script.sh elaborados en clase.

**Comment by JaquelineFloresS** [comment]
Doctor, ya terminé la tarea 1.
Ya incluí el directorio, aunque no se si lo que subí es lo que esperaba que hiciera. Le agradecería me comentara si esta bien o es algo diferente.

**Comment by DrJoseGallardo** [comment]
Estimada alumna:

Para finalizar, revisar que en el readme los archivos llamados script1 y 2 correspondan a lo que subió al directorio SCRIPT. En varias partes uso el termino script 1 para cosas diferentes.

**Comment by JaquelineFloresS** [comment]
Corregido.

**Comment by DrJoseGallardo** [comment]
Excelente.
